package it.unisalento.distributori.domain;
// Generated 11-feb-2017 2.45.16 by Hibernate Tools 4.3.1.Final

/**
 * CategorieForniteId generated by hbm2java
 */
public class CategorieForniteId implements java.io.Serializable {

	private int distributoreId;
	private int categoriaId;

	public CategorieForniteId() {
	}

	public CategorieForniteId(int distributoreId, int categoriaId) {
		this.distributoreId = distributoreId;
		this.categoriaId = categoriaId;
	}

	public int getDistributoreId() {
		return this.distributoreId;
	}

	public void setDistributoreId(int distributoreId) {
		this.distributoreId = distributoreId;
	}

	public int getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(int categoriaId) {
		this.categoriaId = categoriaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategorieForniteId))
			return false;
		CategorieForniteId castOther = (CategorieForniteId) other;

		return (this.getDistributoreId() == castOther.getDistributoreId())
				&& (this.getCategoriaId() == castOther.getCategoriaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDistributoreId();
		result = 37 * result + this.getCategoriaId();
		return result;
	}

}
