package it.unisalento.distributori.domain;
// Generated 11-feb-2017 2.45.16 by Hibernate Tools 4.3.1.Final

/**
 * CategorieFornite generated by hbm2java
 */
public class CategorieFornite implements java.io.Serializable {

	private CategorieForniteId id;
	private Categoria categoria;
	private Distributore distributore;

	public CategorieFornite() {
	}

	public CategorieFornite(CategorieForniteId id, Categoria categoria, Distributore distributore) {
		this.id = id;
		this.categoria = categoria;
		this.distributore = distributore;
	}

	public CategorieForniteId getId() {
		return this.id;
	}

	public void setId(CategorieForniteId id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Distributore getDistributore() {
		return this.distributore;
	}

	public void setDistributore(Distributore distributore) {
		this.distributore = distributore;
	}

}
