package it.unisalento.distributori.domain;
// Generated 21-feb-2017 15.59.54 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dipendente generated by hbm2java
 */
public class Dipendente implements java.io.Serializable {

	private static final long serialVersionUID = 6780999211943973792L;
	private int personaId;
	private Persona persona;
	private String telefono;
	private Set<Rifornisce> rifornisces = new HashSet<Rifornisce>(0);
	private Set<Manutiene> manutienes = new HashSet<Manutiene>(0);
	private Set<Distributore> distributores = new HashSet<Distributore>(0);

	public Dipendente() {
	}

	public Dipendente(Persona persona) {
		this.persona = persona;
	}

	public Dipendente(Persona persona, String telefono, Set<Rifornisce> rifornisces, Set<Manutiene> manutienes, Set<Distributore> distributores) {
		this.persona = persona;
		this.telefono = telefono;
		this.rifornisces = rifornisces;
		this.manutienes = manutienes;
		this.distributores = distributores;
	}

	public int getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(int personaId) {
		this.personaId = personaId;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set<Rifornisce> getRifornisces() {
		return this.rifornisces;
	}

	public void setRifornisces(Set<Rifornisce> rifornisces) {
		this.rifornisces = rifornisces;
	}

	public Set<Manutiene> getManutienes() {
		return this.manutienes;
	}

	public void setManutienes(Set<Manutiene> manutienes) {
		this.manutienes = manutienes;
	}

	public Set<Distributore> getDistributores() {
		return this.distributores;
	}

	public void setDistributores(Set<Distributore> distributores) {
		this.distributores = distributores;
	}

}
