package it.unisalento.distributori.domain;
// Generated 21-feb-2017 15.59.54 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Distributore generated by hbm2java
 */
public class Distributore implements java.io.Serializable {

	private static final long serialVersionUID = -4052653545614640103L;
	private Integer id;
	private Dipendente dipendente;
	private BigDecimal lat;
	private BigDecimal lon;
	private String indirizzo;
	private String posizioneEdificio;
	private Integer stato;
	private Integer numScaffali;
	private Integer numPosti;
	private Set<Acquista> acquistas = new HashSet<Acquista>(0);
	private Set<CategorieFornite> categorieFornites = new HashSet<CategorieFornite>(0);
	private Set<ProdottiErogati> prodottiErogatis = new HashSet<ProdottiErogati>(0);
	private Set<Manutiene> manutienes = new HashSet<Manutiene>(0);
	private Set<Rifornisce> rifornisces = new HashSet<Rifornisce>(0);

	public Distributore() {
	}

	public Distributore(BigDecimal lat, BigDecimal lon) {
		this.lat = lat;
		this.lon = lon;
	}

	public Distributore(Dipendente dipendente, BigDecimal lat, BigDecimal lon, String indirizzo,
			String posizioneEdificio, Integer stato, Integer numScaffali, Integer numPosti, Set<Acquista> acquistas,
			Set<CategorieFornite> categorieFornites, Set<ProdottiErogati> prodottiErogatis, Set<Manutiene> manutienes, Set<Rifornisce> rifornisces) {
		this.dipendente = dipendente;
		this.lat = lat;
		this.lon = lon;
		this.indirizzo = indirizzo;
		this.posizioneEdificio = posizioneEdificio;
		this.stato = stato;
		this.numScaffali = numScaffali;
		this.numPosti = numPosti;
		this.acquistas = acquistas;
		this.categorieFornites = categorieFornites;
		this.prodottiErogatis = prodottiErogatis;
		this.manutienes = manutienes;
		this.rifornisces = rifornisces;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Dipendente getDipendente() {
		return this.dipendente;
	}

	public void setDipendente(Dipendente dipendente) {
		this.dipendente = dipendente;
	}

	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	public BigDecimal getLon() {
		return this.lon;
	}

	public void setLon(BigDecimal lon) {
		this.lon = lon;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getPosizioneEdificio() {
		return this.posizioneEdificio;
	}

	public void setPosizioneEdificio(String posizioneEdificio) {
		this.posizioneEdificio = posizioneEdificio;
	}

	public Integer getStato() {
		return this.stato;
	}

	public void setStato(Integer stato) {
		this.stato = stato;
	}

	public Integer getNumScaffali() {
		return this.numScaffali;
	}

	public void setNumScaffali(Integer numScaffali) {
		this.numScaffali = numScaffali;
	}

	public Integer getNumPosti() {
		return this.numPosti;
	}

	public void setNumPosti(Integer numPosti) {
		this.numPosti = numPosti;
	}

	public Set<Acquista> getAcquistas() {
		return this.acquistas;
	}

	public void setAcquistas(Set<Acquista> acquistas) {
		this.acquistas = acquistas;
	}

	public Set<CategorieFornite> getCategorieFornites() {
		return this.categorieFornites;
	}

	public void setCategorieFornites(Set<CategorieFornite> categorieFornites) {
		this.categorieFornites = categorieFornites;
	}

	public Set<ProdottiErogati> getProdottiErogatis() {
		return this.prodottiErogatis;
	}

	public void setProdottiErogatis(Set<ProdottiErogati> prodottiErogatis) {
		this.prodottiErogatis = prodottiErogatis;
	}

	public Set<Manutiene> getManutienes() {
		return this.manutienes;
	}

	public void setManutienes(Set<Manutiene> manutienes) {
		this.manutienes = manutienes;
	}

	public Set<Rifornisce> getRifornisces() {
		return this.rifornisces;
	}

	public void setRifornisces(Set<Rifornisce> rifornisces) {
		this.rifornisces = rifornisces;
	}

}
