package it.unisalento.distributori.domain;
// Generated 11-feb-2017 2.45.16 by Hibernate Tools 4.3.1.Final

/**
 * FamiglieProdottoId generated by hbm2java
 */
public class FamiglieProdottoId implements java.io.Serializable {

	private int famigliaId;
	private int prodottoId;

	public FamiglieProdottoId() {
	}

	public FamiglieProdottoId(int famigliaId, int prodottoId) {
		this.famigliaId = famigliaId;
		this.prodottoId = prodottoId;
	}

	public int getFamigliaId() {
		return this.famigliaId;
	}

	public void setFamigliaId(int famigliaId) {
		this.famigliaId = famigliaId;
	}

	public int getProdottoId() {
		return this.prodottoId;
	}

	public void setProdottoId(int prodottoId) {
		this.prodottoId = prodottoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FamiglieProdottoId))
			return false;
		FamiglieProdottoId castOther = (FamiglieProdottoId) other;

		return (this.getFamigliaId() == castOther.getFamigliaId())
				&& (this.getProdottoId() == castOther.getProdottoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFamigliaId();
		result = 37 * result + this.getProdottoId();
		return result;
	}

}
