package it.unisalento.distributori.domain;
// Generated 11-feb-2017 2.45.16 by Hibernate Tools 4.3.1.Final

/**
 * FamiglieProdotto generated by hbm2java
 */
public class FamiglieProdotto implements java.io.Serializable {

	private FamiglieProdottoId id;
	private Famiglia famiglia;
	private Prodotto prodotto;

	public FamiglieProdotto() {
	}

	public FamiglieProdotto(FamiglieProdottoId id, Famiglia famiglia, Prodotto prodotto) {
		this.id = id;
		this.famiglia = famiglia;
		this.prodotto = prodotto;
	}

	public FamiglieProdottoId getId() {
		return this.id;
	}

	public void setId(FamiglieProdottoId id) {
		this.id = id;
	}

	public Famiglia getFamiglia() {
		return this.famiglia;
	}

	public void setFamiglia(Famiglia famiglia) {
		this.famiglia = famiglia;
	}

	public Prodotto getProdotto() {
		return this.prodotto;
	}

	public void setProdotto(Prodotto prodotto) {
		this.prodotto = prodotto;
	}

}
