package it.unisalento.distributori.domain;
// Generated 16-feb-2017 10.11.09 by Hibernate Tools 4.3.1.Final

/**
 * FeedbackId generated by hbm2java
 */
public class FeedbackId implements java.io.Serializable {

	private int id;
	private int personaId;

	public FeedbackId() {
	}

	public FeedbackId(int id, int personaId) {
		this.id = id;
		this.personaId = personaId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(int personaId) {
		this.personaId = personaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeedbackId))
			return false;
		FeedbackId castOther = (FeedbackId) other;

		return (this.getId() == castOther.getId()) && (this.getPersonaId() == castOther.getPersonaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getPersonaId();
		return result;
	}

}
