package it.unisalento.distributori.domain;
// Generated 11-feb-2017 2.45.16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String cognome;
	private String email;
	private String password;
	private String tipo;
	private Set feedbacks = new HashSet(0);
	private Set acquistos = new HashSet(0);
	private Dipendente dipendente;

	public Persona() {
	}

	public Persona(String email, String password, String tipo) {
		this.email = email;
		this.password = password;
		this.tipo = tipo;
	}

	public Persona(String nome, String cognome, String email, String password, String tipo, Set feedbacks,
			Set acquistos, Dipendente dipendente) {
		this.nome = nome;
		this.cognome = cognome;
		this.email = email;
		this.password = password;
		this.tipo = tipo;
		this.feedbacks = feedbacks;
		this.acquistos = acquistos;
		this.dipendente = dipendente;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set feedbacks) {
		this.feedbacks = feedbacks;
	}

	public Set getAcquistos() {
		return this.acquistos;
	}

	public void setAcquistos(Set acquistos) {
		this.acquistos = acquistos;
	}

	public Dipendente getDipendente() {
		return this.dipendente;
	}

	public void setDipendente(Dipendente dipendente) {
		this.dipendente = dipendente;
	}

}
